import "./globals.css";
import { Assistant } from "next/font/google";
import ReduxProvider from "@/Redux/ReduxProvider.js";
import { Toaster } from "react-hot-toast";

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
        ${assistantFont.className} antialiased`}
      >
        <ReduxProvider>
          {children}
          <Toaster position="top-center" />
        </ReduxProvider>
      </body>
    </html>
  );
}
